# Welcome to Jekyll!
#
# Site settings
title: "C1pherKn1ght | Red Team Tactics & Offensive Security Mastery"
description: "Portfolio of Travis R. Lee, specializing in Offensive Security and Red Team operations."
baseurl: ""  # Leave empty for GitHub Pages (user/organization site)
url: "https://travrl12.github.io"  # Full URL to your GitHub Pages site
theme: minima

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM  # Use GitHub Flavored Markdown for extra features
  hard_wrap: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag  # Optional, for SEO
  - jekyll-sitemap  # Optional, for sitemap generation

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
